### ISSUE TITLE
Improvement: native-type backend Storage

### ISSUE THREAD

**Issue by bigerl** [TortugaAttack/rdf4cpp#114]
Currently, all datatype values are either stored encoded as canonical strings in the backend or inlined into the NodeBackendHandle. 
While working with inlined values is almost for free, working with values in the backend is expensive. They need to be parsed from string to their native type every time they are used. 

The proposed solution is to customize the backend storage and it's access in such a way that it stores the values instead of the string representation for certain types in the backend. This could be a feature of a type definition, e.g. like inlineable.

**Comment by liss-h** [comment]
Since the registry works on `std::any` anyways there is probably not much point in actually storing the concrete types in the node storage. Except if we want to actually work with concrete types as often as possible which would probably require a complete rewrite of many components an how they interact and is a much more complex undertaking.

(There is also the possibility of storing conrete types and converting to `Any` on any interface boundary but I don't think this is a great idea either, although it does definitely conserve storage space by not having to store a typeid for each literal. But of course we are saving storage already by not storing strings).

So on the basis that `Any`-storage is fine:
I had some time to think about this and I think the capability can be as simple as a flag deciding if you want lexical_form storage or `Any` storage. So string-like things would choose lexical_form storage and numerics would choose any storage

We change the `NodeStorageBackend`, specifically the `LiteralBackend` to be something like the following:

```c++
struct LiteralBackend {
    std::variant<std::any, std::pair<std::string, std::string>>;
};
```

So that the backend either stores a `(lexical_form, language_tag)` pair as before (for all unknown types) or an `std::any` like type for all known types.
There is one interface design problem with that approach: we would need something like an `AnyView` and an accompanying allocator aware implementation of `std::any` for tentris.

The `NodeStorage` gives then out types that look simmilar to this
```c++
struct LiteralBackendView {
    std::variant<AnyView, std::pair<std::string_view, std::string_view>> literal;
};
```
And of course for optimal performance this requires a rewrite of the registry to use `AnyView`, so that we do not have to convert `AnyView` to `std::any` on the interface barrier to the registry.

The `std::variant`s mentioned here could also be replaced by `unions` since the accessors of the node storage can know the active variant at any time. But that would give custom node storage implementations less freedom on omitting to implement `Any`-storage.

**Comment by bigerl** [comment]
During a backend-interaction I see two performance relevant steps right now:
- hash-table lookup (h)
- conversion from/to string (s)

I would expect h>s because it touches more memory locations and has potentially more cache misses. It would make sense to actually measure that.
Side note: If we use a mmap backend these misses might even require a roundtrip to disk. This problem increases with increasing amount of node stored. Otherwise, they most probably reside all within the same page.

So, as long as the string conversion methods are fast we will probably see no relevant difference in performance with the string or type backends. An exception would probably be really large Decimal/Integer/Rational/Real that take longer to parse again than to look up.

On the other hand, as you pointed out, we would save an substantial amount of storage in some use-cases. 

Regarding the interface design: I agree that the `std::any`/`AnyView` makes things a bit easier in the datatypes structure. What I had in mind was a bit different though. 
Node storages should store each native type separately. The view would be simply a reference or pointer to where the value is located in memory. That would mean interface changes in several spots as I see it:
- We would need some standard way, e.g. via inheriting from a `template<literal_datatype> ISpecialNodeStorage`, to tell that a `INodeStorage` implementation is storing a certain datatype explicitly. 
- Interfaces in the typing system would need to check if the current NodeStorage has SpecialNodeStorage and use an interface provided by `ISpecialNodeStorage` to retrieve the cpp types directly. This would safe a from string conversion in many places but would require an additional one to return the lexical form. 
- If a node storage implements a certain ISpecialNodeStorage can in theory be checked with a dynamic_cast. Performance-wise, it would  be better to have a bit mask based on type_ids or something alike.

**Comment by liss-h** [comment]
Another alternative that is effectively a hybrid between the two approaches:

- The node storage has individual storage for conrete types
- the interface boundary is written in terms of `std::any`/`lexical form` and the node storage implementation is responsible for accessing the correct maps and converting from/to `std::any` or the lexical form
