### ISSUE TITLE
statement, triplepattern, quad and quadpattern must not accept blank node variables

### ISSUE THREAD

**Issue by bigerl** [TortugaAttack/rdf4cpp#12]
**Describe the bug**
statement, triplepattern, quad and quadpattern must not accept blank node variables

**Additional context**
[see rdf11-primer](https://www.w3.org/TR/2014/NOTE-rdf11-primer-20140624/#section-triple)

**Comment by AtesComp** [comment]
Why not?  Blank nodes are described in 3.4 of the referenced rdf11-primer and used as both subject and object.  Blank node variables are primary elements in transport file format representations.  If the issue is converting these "blank node variable" representations into actual blank node objects in some data store, then the bug description should reflect that distinction.  Therefore, the code should "accept" blank node variables but convert them to local blank node objects for processing.

Also the "_:a" pattern is used as a variable for blank node queries.

**Comment by bigerl** [comment]
You are right, this one was not precise and is, as of now, outdated on develop. so I'll close it. Thank you for bringing this to attention. 

@AtesComp FYI: rdf4cpp currently explicitly discriminates between actual blank nodes which can be nodes in a graph and anonymous variables which use the same identifiers. The first are represented by instances of the class `rdf4cpp::rdf::BlankNode` while the later are represented by instances of the class `rdf4cpp::rdf::query::Variable` with `is_anonymous() == true`. 
This extends the way SPARQL uses blank nodes and allows to query `QuadPattern`s/`TriplePattern`s with fixed `BlankNode`'s (which doesn't work with SPARQL as blank nodes are interpreted as unprojectable variables). The main purpose of this is to be able to split up operations that otherwise would need to be solved within a single (SPARQL) query. 
(Full) SPARQL support is more of a stretch goal right right now.
