### ISSUE TITLE
Advanced features for IRIs

### ISSUE THREAD

**Issue by nkaralis** [TortugaAttack/rdf4cpp#219]
- IRI validation
- Support for relative and absolute IRIs (https://www.w3.org/TR/2013/REC-sparql11-query-20130321/#QSynIRI)
  - Related to the BASE clause

@bigerl feel free to add more details and/or suggestions

**Comment by bigerl** [comment]
My idea, how we could support this is a `IRIFactory`. 
It has 3 main functions:
- assign or reassign a base
- assign or reassign a shorthand to prefix mapping
- consume `IRIREF`, `PNAME_LN` or `PNAME_NS` and return an rdf4cpp::IRI (see https://www.w3.org/TR/turtle/#grammar-production-iri)

The important aspect that needs to be covered is: If a prefix is relative, e.g., `PREFIX pr: </prrrr/>`, the base, e.g., `BASE: http://base.org/`, must be used to make an absolute IRI, e.g., from `pr:purr` construct `<http://base.org//prrr/purr>`. 
The expected behavior is also described at https://www.w3.org/TR/turtle/#sec-iri (for an example see Example 8)

We need to specify a "default base URI", as described here: https://datatracker.ietf.org/doc/html/rfc3986#section-5.1.4
I suggest to make it configurable in the constructor of the factory and default to http://example.org/ . 

Open questions from my side: 
- how (and where) do we handle RDF Uri references: 
  > The set of RDF terms defined in RDF Concepts and Abstract Syntax includes RDF URI references while SPARQL terms include IRIs. RDF URI references containing "<", ">", '"' (double quote), space, "{", "}", "|", "\", "^", and "`" are not IRIs. The behavior of a SPARQL query against RDF statements composed of such RDF URI references is not defined.
